### ISSUE TITLE
STM32H7x3: Ethernet_MAC peripheral broken

### ISSUE THREAD

**Issue by ehntoo** [adamgreig/stm32-rs#41]
From what I can tell by the reference manual, the STM32H7x3 uses the same ethernet MAC as the STM32F7x9 and company. The SVD is seriously broken in this regard - it lists the DMA-related registers under "Ethernet_MAC" rather than under an "Ethernet_DMA" peripheral, and all of the other registers are missing entirely.

Is the preferred method for fixing an error this egregious to use the normal yaml patching mechanisms? Just seeking input before I put together a PR. :)

*edit*
Upon further inspection, the peripheral is _not_ the same as the F7x9. The SVD issues still stand, though.

**Comment by adamgreig** [comment]
Yikes, that's shocking.

Yes, the normal YAML patching mechanisms would suffice to fix this - you can add entire new peripherals with new registers with new fields, and probably just wholesale delete the existing Ethernet_MAC since it's full of lies. For an example of doing this, check out [stm32f7x9](https://github.com/adamgreig/stm32-rs/blob/master/devices/stm32f7x9.yaml#L3) where we have to add an ADC_Common peripheral. A PR to fix it would be very appreciated!

This sort of thing you might hope ST themselves would fix with an updated SVD file but I wouldn't hold your breath.

**Comment by ehntoo** [comment]
Fixed by #42 :)
